weights = {
    'FORMACAO-ACADEMICA-TITULACAO' : {'POS-DOUTORADO': 10, 'LIVRE-DOCENCIA': 8, 'DOUTORADO': 7, 'MESTRADO': 3},
    'PROJETO-DE-PESQUISA' : {'PESQUISA': 2, 'DESENVOLVIMENTO': 2},
    'PRODUCAO-BIBLIOGRAFICA' : {
        'ARTIGOS-PUBLICADOS': {'A1': 11, 'A2': 11, 'B1': 8, 'B2': 8, 'B3': 6, 'B4': 2, 'B5': 2, 'C': 0.5, 'NAO-ENCONTRADO': 0.5},
        'TRABALHOS-EM-EVENTOS': {
            'INTERNACIONAL': { 'COMPLETO': 2, 'RESUMO_EXPANDIDO': 0.3, 'RESUMO': 0.3 },
            'NACIONAL': { 'COMPLETO': 1, 'RESUMO_EXPANDIDO': 0.2, 'RESUMO': 0.2 },
            'REGIONAL': { 'COMPLETO': 0.3, 'RESUMO_EXPANDIDO': 0.1, 'RESUMO': 0.1 },
            'LOCAL': { 'COMPLETO': 0.2, 'RESUMO_EXPANDIDO': 0.1, 'RESUMO': 0.1 },
            'NAO_INFORMADO': { 'COMPLETO': 0, 'RESUMO_EXPANDIDO': 0, 'RESUMO': 0 },
        },
        'LIVROS-E-CAPITULOS': {
            'LIVRO-PUBLICADO-OU-ORGANIZADO': {
                'LIVRO_PUBLICADO': 8,
                'LIVRO_ORGANIZADO_OU_EDICAO': 3,
                'NAO_INFORMADO': 0,
            },
            'CAPITULO-DE-LIVRO-PUBLICADO': 2,
        },
        'DEMAIS-TIPOS-DE-PRODUCAO-BIBLIOGRAFICA': { 'TRADUCAO': 2 },
    },
    'PRODUCAO-TECNICA': {
        'SOFTWARE': 2,
        'PATENTE': {'DEPOSITADA': 2, 'CONCEDIDA': 8},
        'PRODUTO-TECNOLOGICO': 2,
        'PROCESSOS-OU-TECNICAS': 2,
        'TRABALHO-TECNICO': 0.2,
    },
    'OUTRA-PRODUCAO': {
        'PRODUCAO-ARTISTICA-CULTURAL': {
            'APRESENTACAO-DE-OBRA-ARTISTICA': 1,
            'COMPOSICAO-MUSICAL': 2,
            'OBRA-DE-ARTES-VISUAIS': 2,
        },
        'ORIENTACOES-CONCLUIDAS': {
            'ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO': 7,
            'ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO': 5,
            'ORIENTACOES-CONCLUIDAS-PARA-MESTRADO': 2,
            'OUTRAS-ORIENTACOES-CONCLUIDAS': {
                'MONOGRAFIA_DE_CONCLUSAO_DE_CURSO_APERFEICOAMENTO_E_ESPECIALIZACAO': 0.8,
                'TRABALHO_DE_CONCLUSAO_DE_CURSO_GRADUACAO': 0.5,
                'INICIACAO_CIENTIFICA': 0.5,
                'ORIENTACAO-DE-OUTRA-NATUREZA': 0,
            },
        },
    },
}
